services:
  api:
    build: .
    image: rioni-api-nginx
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: rioni_db
      DB_SCHEMA: rioni_dev
      DB_USERNAME: rioni_db
      DB_PASSWORD: ${DB_PASSWORD:-xDspl!pzoxI98^zLPz_02kLk}
    ports:
      - '8081:8080'
    restart: always
    networks:
      - dev
networks:
  dev:
    external: true