spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/rioni_db?currentSchema=rioni_dev
spring.datasource.username=rioni_db
spring.datasource.password=xDspl!pzoxI98^zLPz_02kLk
spring.jpa.properties.hibernate.default_schema=rioni_dev
spring.flyway.schemas=rioni_dev
spring.flyway.default-schema=rioni_dev
server.port=8082