spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/rioni_db
spring.datasource.username=rioni_db
spring.datasource.password=xDspl!pzoxI98^zLPz_02kLk
spring.jpa.properties.hibernate.default_schema=rioni_dev 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql