spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}
spring.flyway.schemas=${DB_SCHEMA}
spring.flyway.default-schema=${DB_SCHEMA}
app.logos.base-url=http://51.250.101.25:8081
app.avatars.base-url=http://51.250.101.25:8081/profile/avatars/
app.avatars.storage-path=/app/src/main/resources/static/profile/avatars
app.uploads.base-url=http://51.250.101.25:8081/uploads/
app.uploads.storage-path=/app/uploads