ALTER TABLE profile ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
ALTER TABLE profile ADD COLUMN IF NOT EXISTS company_industry VARCHAR(255);
ALTER TABLE profile ADD COLUMN IF NOT EXISTS company_position VARCHAR(255);
ALTER TABLE profile ADD COLUMN IF NOT EXISTS company_phone VARCHAR(255);
ALTER TABLE profile ADD COLUMN IF NOT EXISTS company_website VARCHAR(255);
ALTER TABLE profile ADD COLUMN IF NOT EXISTS is_npo BOOLEAN DEFAULT FALSE;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS is_ngo BOOLEAN DEFAULT FALSE;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS is_self_employed BOOLEAN DEFAULT FALSE;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS is_not_working BOOLEAN DEFAULT FALSE;